### ISSUE TITLE
Plug doesn't work with Cura 5.1.0 - ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by jallen2281** [Razor10021990/CuraSnapmakerSender#11]
Below is the log entry when the plugins are loaded on startup due to cura now using PyQT6 instead of 5. 

`2022-07-30 10:55:33,598 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: Exception: Import error loading module CuraSnapmakerSender
2022-07-30 10:55:33,599 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: Traceback (most recent call last):
2022-07-30 10:55:33,600 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "UM\PluginRegistry.py", line 730, in _findPlugin
2022-07-30 10:55:33,600 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     module = imp.load_module(plugin_id, file, path, desc)  # type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2022-07-30 10:55:33,601 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 245, in load_module
2022-07-30 10:55:33,601 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 217, in load_package
2022-07-30 10:55:33,601 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 719, in _load
2022-07-30 10:55:33,602 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-07-30 10:55:33,602 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-07-30 10:55:33,603 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-07-30 10:55:33,603 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\jalle\AppData\Roaming\cura\5.1\plugins\CuraSnapmakerSender\CuraSnapmakerSender\__init__.py", line 6, in <module>
2022-07-30 10:55:33,604 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from . import CuraSnapmakerSenderPlugin
2022-07-30 10:55:33,604 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\jalle\AppData\Roaming\cura\5.1\plugins\CuraSnapmakerSender\CuraSnapmakerSender\CuraSnapmakerSenderPlugin.py", line 10, in <module>
2022-07-30 10:55:33,605 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from PyQt5.QtWidgets import QPushButton
2022-07-30 10:55:33,605 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: ModuleNotFoundError: No module named 'PyQt5'
2022-07-30 10:55:33,606 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [824]: Could not find plugin CuraSnapmakerSender
2022-07-30 10:55:33,610 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: Exception: Import error loading module CuraSnapmakerSender
2022-07-30 10:55:33,611 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: Traceback (most recent call last):
2022-07-30 10:55:33,611 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "UM\PluginRegistry.py", line 730, in _findPlugin
2022-07-30 10:55:33,612 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     module = imp.load_module(plugin_id, file, path, desc)  # type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2022-07-30 10:55:33,612 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 245, in load_module
2022-07-30 10:55:33,613 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 217, in load_package
2022-07-30 10:55:33,613 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 719, in _load
2022-07-30 10:55:33,613 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-07-30 10:55:33,614 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-07-30 10:55:33,614 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-07-30 10:55:33,615 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\jalle\AppData\Roaming\cura\5.1\plugins\CuraSnapmakerSender\CuraSnapmakerSender\__init__.py", line 6, in <module>
2022-07-30 10:55:33,615 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from . import CuraSnapmakerSenderPlugin
2022-07-30 10:55:33,615 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\jalle\AppData\Roaming\cura\5.1\plugins\CuraSnapmakerSender\CuraSnapmakerSender\CuraSnapmakerSenderPlugin.py", line 10, in <module>
2022-07-30 10:55:33,616 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from PyQt5.QtWidgets import QPushButton
2022-07-30 10:55:33,616 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: ModuleNotFoundError: No module named 'PyQt5'
2022-07-30 10:55:33,618 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [529]: Exception: Error loading plugin CuraSnapmakerSender:
2022-07-30 10:55:33,618 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [529]: NoneType: None
`

The suggested code block to keep compatibility across versions would use a try: except ImportError: something like this:

`try:
    from PyQt6.QtCore import QByteArray,QIODevice,QBuffer
except ImportError:
    from PyQt5.QtCore import QByteArray,QIODevice,QBuffer
`

I was able to get the plugin loading and may submit a pull, however there are further updates needed first because of this error:

2022-07-30 11:31:40,848 - WARNING - [MainThread] UM.PluginRegistry.loadPlugin [459]: Plugin [CuraSnapmakerSender] with supported sdk versions [['7.4.0', '7.3.0', '7.2.0', '7.1.0']] is incompatible with the current sdk version [8.1.0].

**Comment by Razor10021990** [comment]
I have also started porting it. I have it already running. But the
possibility to set Custom IP addresses is not yet finished, because I am
not able to get the Table working. Then I got caught away by my newly born
daughter. I could push the changes, if you are willing to work on the ip
Address table.

Jared Allen ***@***.***> schrieb am Sa., 30. Juli 2022, 17:39:

**Comment by jallen2281** [comment]
I'd definitely be happy to put some more effort towards it, I personally
use this plugin on a regular basis.

Congratulations on your daughter!

**Comment by Filmman586** [comment]
Congratulations on your daughter! 😊

**Comment by jallen2281** [comment]
> I could push the changes, if you are willing to work on the ip Address table.
@Razor10021990  Were you still planning on pushing your changes for this? I'm definitely interested in contributing.

**Comment by Razor10021990** [comment]
@jallen2281 
I have now pushed the branch "cura5_unfinished"

It's basically just missing a working UI for changing the settings(add printers manually and toggle the automatic search). Everything else is working so far. (Atleast the last time i have tried it with cura5.0)

**Comment by RaBuAc** [comment]
@Razor10021990 
I've installed Cura 5.6.0 and copied the file from the "unfinished" branch to the cura plugin directory. When I now start cura it finds the plugin and I have the submenue CuraSnapmakerSender->Settings which does not open any setting window (which I understand is not implemented yet). 
Anyhow, how do I get the IP address configured? I have my snapmaker printer installed as a local printer as when I try to install it as a networked printer and add the IP address an error comes up "printer is not responding". 
I would be glad if you can direct me how to configure your plugin.
Many thanks!

**Comment by jallen2281** [comment]
The official snap maker plugin works fine no need for this anymore.

**Comment by RaBuAc** [comment]
@jallen2281 
Many thanks.
But I do had already the snapmaker plugin installed, by don't got a prompt "Send to <IP>"! I wonder what I'm missing..

**Comment by Razor10021990** [comment]
For that I had implemented the ability to set ip addresses manually, which
the official plugin is still lacking.

But I won't update to the new cura versions, because I wasn't able to Port
the existing UI to QT5. And I am refusing to learn more Qt to implement it
the way QT5 wants it.

RaBuAc ***@***.***> schrieb am Mi., 21. Feb. 2024, 16:21:

**Comment by jallen2281** [comment]
Because QT is a not very widely used language and there's no point in learning it!

**Comment by Razor10021990** [comment]
I just don't need it for my life.

Jared Allen ***@***.***> schrieb am Mi., 21. Feb. 2024, 21:00:

**Comment by jallen2281** [comment]
> @jallen2281 
> Many thanks.
> But I do had already the snapmaker plugin installed, by don't got a prompt "Send to <IP>"! I wonder what I'm missing..

Make sure you have the other snap maker plugins uninstalled and the latest version of Cura. Also make sure your printer and your computer are on the same subnet, and on the same (wireless)network. Restart your printer, if you are still having issues, follow the troubleshooting/ installation directions on the snap maker forum.
